name: Node.js CI

# Pipeline qachon ishga tushadi
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

# Asosiy ish (job)
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v4

      - name: Node.js o‘rnatish
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Kutubxonalarni o‘rnatish
        run: npm install --include=dev

      - name: Testlarni ishga tushirish
        run: npm test
